export type ProductId =
  | "luna"
  | "retina-flve"
  | "digital-rm"
  | "medpac"
  | "teleicu"
  | "pacman"
  | "interface-board";

export type Month = "PRIOR" | "AUGUST" | "SEPTEMBER" | "OCTOBER" | "NOVEMBER" | "DECEMBER";

export type Product = {
  id: ProductId;
  name: string;
  division: "Software" | "Hardware";
  description: string;
  image: string;
  imageAlt: string;
  imagePosition?: string;
  imageFit?: "cover" | "contain";
  accent: string;
  ink: string;
  wash: string;
};

export type Milestone = {
  slug: string;
  productId: ProductId;
  month: Month;
  exactDate: string;
  version?: string;
  title: string;
  kpi: string;
  description: string;
  basis: string;
  status: "Verified" | "Committed" | "Target" | "Proposed" | "Approved" | "In development";
  release?: true;
};

export const months: Month[] = ["PRIOR", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"];

export const products: Product[] = [
  {
    id: "luna",
    name: "LUNA",
    division: "Software",
    description: "Patient-facing healthcare AI assistant",
    image: "/luna-avatar.png",
    imageAlt: "LUNA assistant avatar",
    imagePosition: "50% 22%",
    accent: "#2f80ed",
    ink: "#123f78",
    wash: "#eaf4ff",
  },
  {
    id: "retina-flve",
    name: "Retina-FLVE",
    division: "Software",
    description: "AI vision for liveness, verification + eKYC",
    image: "/retina-flve-ai-vision.png",
    imageAlt: "AI vision eye formed from neural network nodes",
    imagePosition: "50% 50%",
    accent: "#dc7a1f",
    ink: "#7c420d",
    wash: "#fff2e5",
  },
  {
    id: "digital-rm",
    name: "DigitalRM",
    division: "Software",
    description: "Aria · universal personal digital employee",
    image: "/digitalrm-logo.png",
    imageAlt: "DigitalRM logo",
    imageFit: "contain",
    accent: "#8759e8",
    ink: "#4f278e",
    wash: "#f2ecff",
  },
  {
    id: "medpac",
    name: "MedPAC",
    division: "Software",
    description: "Enterprise PACS, VNA + reporting workflow",
    image: "/medpac-logo.png",
    imageAlt: "MedPAC product logo",
    imageFit: "contain",
    accent: "#23a36d",
    ink: "#145d40",
    wash: "#e8f8ef",
  },
  {
    id: "teleicu",
    name: "TeleICU",
    division: "Software",
    description: "Remote critical-care command centre",
    image: "/teleicu-command-center.png",
    imageAlt: "Doctor monitoring live patients and vital signs in a TeleICU command centre",
    imagePosition: "50% 46%",
    accent: "#d94b8b",
    ink: "#812a55",
    wash: "#ffedf6",
  },
  {
    id: "pacman",
    name: "PacMan Node",
    division: "Hardware",
    description: "MedPAC DICOM sync node · OEM delivered",
    image: "/pacman-logo.png",
    imageAlt: "PacMan DICOM Sync product logo",
    imageFit: "contain",
    accent: "#5570dc",
    ink: "#30458d",
    wash: "#edf0ff",
  },
  {
    id: "interface-board",
    name: "Interface Board",
    division: "Hardware",
    description: "Purpose-built embedded interface · OEM delivered",
    image: "/interface-board-embedded.png",
    imageAlt: "Illustration of a purpose-built embedded interface board",
    imagePosition: "50% 50%",
    accent: "#168f91",
    ink: "#0b5f61",
    wash: "#e7f8f7",
  },
];

export const milestones: Milestone[] = [
  {
    slug: "luna-live-launch",
    productId: "luna",
    month: "AUGUST",
    exactDate: "August 1, 2026",
    version: "Launch",
    title: "Web, iOS, Android + training",
    kpi: "Production channels live; staff training complete",
    description: "Launch LUNA for Labaid Cancer across web, iOS and Android and complete on-site operational training.",
    basis: "LUNA launch deck + production QA and release evidence",
    status: "Verified",
    release: true,
  },
  {
    slug: "luna-akhil-prism",
    productId: "luna",
    month: "AUGUST",
    exactDate: "August 15, 2026",
    title: "AKHIL API + Prism dashboard",
    kpi: "Login-attributed token use visible in Prism",
    description: "Connect the AKHIL cloud API, attribute token use by login and expose that operating view in Labaid Prism.",
    basis: "LUNA launch deck + commercial commitment",
    status: "Committed",
  },
  {
    slug: "luna-doctors-edition",
    productId: "luna",
    month: "SEPTEMBER",
    exactDate: "September 15, 2026",
    title: "Doctors edition",
    kpi: "Patient summary generated from the conversation",
    description: "Release the doctors edition with a concise patient summary derived from the LUNA conversation.",
    basis: "LUNA launch deck target",
    status: "Target",
  },
  {
    slug: "luna-reports-erx",
    productId: "luna",
    month: "OCTOBER",
    exactDate: "October 15, 2026",
    title: "Reports + e-prescription",
    kpi: "Test-report and e-prescription journeys usable",
    description: "Extend LUNA to test reports, e-prescription and a wider range of governed hospital queries.",
    basis: "LUNA launch deck target",
    status: "Target",
  },
  {
    slug: "retina-flve-ekyc-delivered",
    productId: "retina-flve",
    month: "PRIOR",
    exactDate: "January 15, 2026",
    version: "Version 1.0",
    title: "Delivered · Labaid InsureTech eKYC",
    kpi: "Production eKYC delivered",
    description: "Retina-FLVE provides face liveness and identity verification for the Labaid InsureTech eKYC journey.",
    basis: "Management delivery record + FLVE and InsureTech implementation",
    status: "Verified",
    release: true,
  },
  {
    slug: "retina-flve-ekyc-v11",
    productId: "retina-flve",
    month: "SEPTEMBER",
    exactDate: "September 10, 2026",
    version: "Version 1.1",
    title: "Identity-match + assurance upgrade",
    kpi: "Reference match returned; full eKYC regression passes",
    description: "Wire the trusted reference-image face match into completion and verify the complete InsureTech eKYC journey.",
    basis: "Management upgrade date + documented InsureTech/FLVE integration gap",
    status: "Target",
    release: true,
  },
  {
    slug: "digital-rm-v1",
    productId: "digital-rm",
    month: "SEPTEMBER",
    exactDate: "September 1, 2026",
    version: "v1.0",
    title: "Managed baseline release",
    kpi: "Core acceptance journey passes end to end",
    description: "Package Aria's delegated tasks, notes, contacts, daily brief and audited writes as the initial managed release.",
    basis: "Management release train + implemented DigitalRM capabilities",
    status: "Target",
    release: true,
  },
  {
    slug: "digital-rm-v2",
    productId: "digital-rm",
    month: "OCTOBER",
    exactDate: "October 1, 2026",
    version: "v2.0",
    title: "Connected work release",
    kpi: "Enabled-connection smoke matrix passes",
    description: "Package web, messaging, MCP and API connections so Aria can carry governed work across enabled channels and tools.",
    basis: "Management release train + implemented DigitalRM connections",
    status: "Target",
    release: true,
  },
  {
    slug: "digital-rm-v3",
    productId: "digital-rm",
    month: "NOVEMBER",
    exactDate: "November 1, 2026",
    version: "v3.0",
    title: "Final production release",
    kpi: "Release suites pass; proactive and approval flows verified",
    description: "Complete Aria's production release with schedules, briefings, meeting capture, owner memory, approvals, tenant controls, audit, documents and the full user interface.",
    basis: "Management release train + implemented DigitalRM production, proactive and safety features",
    status: "Target",
    release: true,
  },
  {
    slug: "medpac-srs-architecture",
    productId: "medpac",
    month: "AUGUST",
    exactDate: "August 10, 2026",
    title: "SRS approval",
    kpi: "SRS baseline approved",
    description: "Approve the enterprise PACS and VNA requirements baseline so scope and architecture decisions are controlled.",
    basis: "Management date + MedPAC enterprise SRS",
    status: "Target",
  },
  {
    slug: "medpac-screens-app",
    productId: "medpac",
    month: "SEPTEMBER",
    exactDate: "September 1, 2026",
    title: "Screens + doctor app ready",
    kpi: "Daily screens complete; phone app opens viewer",
    description: "Complete daily worklist, scheduling and administration screens plus a doctor app that opens the existing MedView mobile viewer.",
    basis: "MedPAC master plan",
    status: "In development",
  },
  {
    slug: "medpac-v10-release",
    productId: "medpac",
    month: "OCTOBER",
    exactDate: "October 1, 2026",
    version: "v1",
    title: "Early release",
    kpi: "Real-device imaging journey + complete audit pass",
    description: "A real device gets its worklist, sends the study unaided and receives custody confirmation; the matched study is viewed, measured, reported, signed and retrieved with a complete audit trail.",
    basis: "MedPAC SRS R1 live-site acceptance test",
    status: "Target",
    release: true,
  },
  {
    slug: "medpac-v11",
    productId: "medpac",
    month: "NOVEMBER",
    exactDate: "November 1, 2026",
    version: "v2",
    title: "First feature release",
    kpi: "Reviewed AI + tamper detection + tier retrieval pass",
    description: "Each draft AI finding is accepted or rejected with disposition, the signed report detects alteration and a tier-moved study remains retrievable.",
    basis: "MedPAC SRS R2 acceptance test",
    status: "Target",
    release: true,
  },
  {
    slug: "medpac-v12-his",
    productId: "medpac",
    month: "DECEMBER",
    exactDate: "December 1, 2026",
    version: "v3",
    title: "Second feature release",
    kpi: "Idempotent HIS round-trip + unattended edge run pass",
    description: "A hospital order creates the MedPAC worklist automatically, the signed report returns without manual work, duplicates are not reprocessed and the purpose-built edge node completes an unattended site run.",
    basis: "MedPAC SRS R3 live-site acceptance test",
    status: "Target",
    release: true,
  },
  {
    slug: "teleicu-define",
    productId: "teleicu",
    month: "SEPTEMBER",
    exactDate: "September 28–October 9, 2026",
    title: "Clinical + device definition",
    kpi: "Pilot boundary agreed",
    description: "Agree the pilot beds, devices, signals, alerts and clinical response workflow before implementation begins.",
    basis: "Management date envelope; scope is a planning proposal pending SRS",
    status: "Proposed",
  },
  {
    slug: "teleicu-gateway-alpha",
    productId: "teleicu",
    month: "OCTOBER",
    exactDate: "October 10–25, 2026",
    version: "Alpha",
    title: "Gateway + dashboard",
    kpi: "Representative device signals visible",
    description: "Ingest representative bedside-device signals and display them in the remote critical-care command dashboard.",
    basis: "Management date envelope; scope is a planning proposal pending SRS",
    status: "Proposed",
  },
  {
    slug: "teleicu-alert-context",
    productId: "teleicu",
    month: "OCTOBER",
    exactDate: "October 26–November 8, 2026",
    title: "Alerts + patient/device context",
    kpi: "Actionable alert path works",
    description: "Connect patient context, the reason for an alert and acknowledgement by the remote response team.",
    basis: "Management date envelope; scope is a planning proposal pending SRS",
    status: "Proposed",
  },
  {
    slug: "teleicu-lab-uat",
    productId: "teleicu",
    month: "NOVEMBER",
    exactDate: "November 9–20, 2026",
    title: "Integrated lab + clinical UAT",
    kpi: "Core scenarios pass safely",
    description: "Run the complete monitored-bed journey with clinicians, representative devices and integrated hardware.",
    basis: "Management date envelope; scope is a planning proposal pending SRS",
    status: "Proposed",
  },
  {
    slug: "teleicu-pilot-mvp",
    productId: "teleicu",
    month: "DECEMBER",
    exactDate: "December 1, 2026",
    version: "MVP",
    title: "Pilot-ready release",
    kpi: "Limited pilot can start",
    description: "Prepare a controlled TeleICU pilot for named beds, users, devices, response rules and support hours.",
    basis: "Management 1 December target; pilot scope is proposed pending SRS",
    status: "Target",
    release: true,
  },
  {
    slug: "pacman-spec-partner",
    productId: "pacman",
    month: "AUGUST",
    exactDate: "August 1–31, 2026",
    title: "Specification + OEM partner",
    kpi: "OEM development and delivery agreement signed",
    description: "Freeze the node requirements and contract the Chinese OEM partner for engineering, manufacture and delivery.",
    basis: "MedPAC hardware master plan + management OEM direction",
    status: "Target",
  },
  {
    slug: "pacman-evt-units",
    productId: "pacman",
    month: "SEPTEMBER",
    exactDate: "September 1–October 15, 2026",
    version: "EVT stage",
    title: "Units + software image",
    kpi: "Units boot; PacMan, thermal + throughput checks pass",
    description: "Build representative engineering units and verify the PacMan software image, thermal behavior and DICOM throughput on the OEM hardware.",
    basis: "MedPAC hardware master plan + existing PacMan software",
    status: "Target",
  },
  {
    slug: "pacman-live-site-trial",
    productId: "pacman",
    month: "OCTOBER",
    exactDate: "October 15–November 20, 2026",
    title: "Live-site trial",
    kpi: "Site workload remains stable",
    description: "Run DICOM synchronisation under a real hospital workload and record stability, thermal and service behaviour.",
    basis: "MedPAC hardware master plan + existing PacMan software",
    status: "Target",
  },
  {
    slug: "pacman-mfg-ready",
    productId: "pacman",
    month: "DECEMBER",
    exactDate: "December 1, 2026",
    title: "Manufacturing-ready package",
    kpi: "Repeatable OEM build pack released",
    description: "Release the repeatable OEM manufacturing, test, software-image, installer, spares and replacement package.",
    basis: "MedPAC hardware master plan + management OEM direction",
    status: "Target",
    release: true,
  },
  {
    slug: "board-interface-spec",
    productId: "interface-board",
    month: "SEPTEMBER",
    exactDate: "September 28–October 9, 2026",
    title: "Interface + electrical specification",
    kpi: "Device boundary frozen with OEM partner",
    description: "Freeze electrical, protocol, isolation and connector requirements with the embedded-system OEM partner.",
    basis: "Management date envelope; OEM engineering proposal pending approved specification",
    status: "Proposed",
  },
  {
    slug: "board-evt1",
    productId: "interface-board",
    month: "OCTOBER",
    exactDate: "October 5–30, 2026",
    version: "EVT 1",
    title: "Schematic, PCB, firmware + build",
    kpi: "EVT 1 boards delivered by OEM",
    description: "Complete the purpose-built schematic, PCB, embedded firmware and first OEM engineering build.",
    basis: "Management date envelope; OEM engineering proposal pending approved specification",
    status: "Proposed",
  },
  {
    slug: "board-bring-up",
    productId: "interface-board",
    month: "OCTOBER",
    exactDate: "October 26–November 13, 2026",
    title: "Bring-up + bench checks",
    kpi: "Critical interfaces pass",
    description: "Power and test the OEM board, then verify every critical medical-device interface on the bench.",
    basis: "Management date envelope; OEM engineering proposal pending approved specification",
    status: "Proposed",
  },
  {
    slug: "board-integrated-lab",
    productId: "interface-board",
    month: "NOVEMBER",
    exactDate: "November 9–20, 2026",
    title: "Integrated hardware/software lab",
    kpi: "End-to-end device path repeatable",
    description: "Prove the complete bedside-device to TeleICU data path with the interface hardware and software together.",
    basis: "Management date envelope; OEM engineering proposal pending approved specification",
    status: "Proposed",
  },
  {
    slug: "board-pilot-ready",
    productId: "interface-board",
    month: "DECEMBER",
    exactDate: "December 1, 2026",
    version: "EVT pilot",
    title: "Pilot-ready package",
    kpi: "Controlled OEM pilot pack delivered",
    description: "Deliver the controlled EVT hardware, firmware and test package required for the TeleICU pilot.",
    basis: "Management 1 December target; EVT pilot scope is proposed",
    status: "Target",
    release: true,
  },
];

export const productById = Object.fromEntries(products.map((product) => [product.id, product])) as Record<ProductId, Product>;
export const milestoneBySlug = Object.fromEntries(milestones.map((milestone) => [milestone.slug, milestone])) as Record<string, Milestone>;
