export type ProductId =
  | "luna"
  | "digital-rm"
  | "medpac"
  | "teleicu"
  | "pacman"
  | "interface-board";

export type Month = "AUGUST" | "SEPTEMBER" | "OCTOBER" | "NOVEMBER" | "DECEMBER";

export type EvidenceState = "verified" | "committed" | "target" | "external";

export type Product = {
  id: ProductId;
  name: string;
  shortName: string;
  division: "Software" | "Hardware";
  tagline: string;
  status: string;
  image: string;
  imageAlt: string;
  imageCredit: string;
  imageCreditUrl: string;
  accent: string;
  ink: string;
  wash: string;
};

export type Reference = {
  id: string;
  title: string;
  publisher: string;
  url: string;
  use: string;
};

export type Milestone = {
  slug: string;
  productId: ProductId;
  month: Month;
  date: string;
  version?: string;
  title: string;
  kpi: string;
  plainMeaning: string;
  businessValue: string;
  successSignals: [string, string, string];
  evidence: [string, string, string];
  dependency: string;
  state: EvidenceState;
  release?: boolean;
  sourceIds: string[];
};

export const months: Month[] = ["AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"];

export const products: Product[] = [
  {
    id: "luna",
    name: "LUNA",
    shortName: "LU",
    division: "Software",
    tagline: "Consumer AI assistant",
    status: "Live",
    image: "/luna-clinical-ai.jpg",
    imageAlt: "Doctor explaining a medical image on a tablet",
    imageCredit: "Vitaly Gariev · Unsplash",
    imageCreditUrl: "https://unsplash.com/photos/doctor-shows-patient-medical-scan-on-tablet-EXOkTjoKkoU",
    accent: "#2f80ed",
    ink: "#0e4c97",
    wash: "#eaf4ff",
  },
  {
    id: "digital-rm",
    name: "Digital RM",
    shortName: "DR",
    division: "Software",
    tagline: "Care relationship management",
    status: "Monthly releases",
    image: "/digital-rm-care.jpg",
    imageAlt: "Two clinicians coordinating care on a tablet",
    imageCredit: "Nappy · Unsplash",
    imageCreditUrl: "https://unsplash.com/photos/a-doctor-and-a-patient-looking-at-a-tablet-DbCfSrTnflA",
    accent: "#f48732",
    ink: "#8a410d",
    wash: "#fff1e4",
  },
  {
    id: "medpac",
    name: "MedPAC",
    shortName: "MP",
    division: "Software",
    tagline: "PACS release train",
    status: "14 gates open",
    image: "/medpac-imaging.jpg",
    imageAlt: "Clinician operating a medical imaging scanner",
    imageCredit: "Accuray · Unsplash",
    imageCreditUrl: "https://unsplash.com/photos/a-doctor-checking-a-patient-36i9vuZrVjc",
    accent: "#2bb673",
    ink: "#14603d",
    wash: "#e8f8ef",
  },
  {
    id: "teleicu",
    name: "TeleICU",
    shortName: "TI",
    division: "Software",
    tagline: "Remote critical-care visibility",
    status: "New build",
    image: "/teleicu-monitoring.jpg",
    imageAlt: "Clinician operating a bedside patient monitor",
    imageCredit: "Alexander Mass · Unsplash",
    imageCreditUrl: "https://unsplash.com/photos/a-person-adjusts-a-medical-monitor-in-a-tiled-room-Scr5C6EGz9I",
    accent: "#e95b9c",
    ink: "#8a2859",
    wash: "#ffedf6",
  },
  {
    id: "pacman",
    name: "PacMan Node",
    shortName: "PN",
    division: "Hardware",
    tagline: "Edge imaging appliance",
    status: "Partner gate",
    image: "/hardware-board.jpg",
    imageAlt: "Close view of a blue embedded circuit board",
    imageCredit: "Daniel Andrade · Unsplash",
    imageCreditUrl: "https://unsplash.com/photos/blue-circuit-board-0IZC2kYhYIo",
    accent: "#8066f6",
    ink: "#4c3598",
    wash: "#f0edff",
  },
  {
    id: "interface-board",
    name: "Interface Board",
    shortName: "IB",
    division: "Hardware",
    tagline: "TeleICU device interface",
    status: "EVT",
    image: "/hardware-board.jpg",
    imageAlt: "Close view of a blue embedded circuit board",
    imageCredit: "Daniel Andrade · Unsplash",
    imageCreditUrl: "https://unsplash.com/photos/blue-circuit-board-0IZC2kYhYIo",
    accent: "#16aaa9",
    ink: "#0c6666",
    wash: "#e7f8f7",
  },
];

export const references: Reference[] = [
  {
    id: "ahrq-care",
    title: "Care Coordination Measures Atlas",
    publisher: "AHRQ",
    url: "https://www.ahrq.gov/ncepcr/care/coordination/atlas/chapter3.html",
    use: "Frames accountability, communication, transitions, proactive care plans, and follow-up.",
  },
  {
    id: "fhir",
    title: "FHIR overview",
    publisher: "HL7",
    url: "https://fhir.hl7.org/fhir/overview.html",
    use: "Reference for structured, interoperable exchange of healthcare information.",
  },
  {
    id: "dicom",
    title: "DICOM overview",
    publisher: "DICOM Standard",
    url: "https://www.dicomstandard.org/using/overview",
    use: "Reference for producing, storing, displaying, sending, querying, and retrieving medical images.",
  },
  {
    id: "who-telemedicine",
    title: "Consolidated telemedicine implementation guide",
    publisher: "World Health Organization",
    url: "https://www.who.int/publications/i/item/9789240059184",
    use: "Frames planning, implementation, routine monitoring, end-user feedback, and continuous improvement.",
  },
  {
    id: "who-accessibility",
    title: "Global standard for accessibility of telehealth services",
    publisher: "WHO · ITU",
    url: "https://www.who.int/publications/i/item/9789240050464",
    use: "Accessibility reference for inclusive telehealth service design.",
  },
  {
    id: "fda-design",
    title: "Design control guidance for medical device manufacturers",
    publisher: "U.S. FDA",
    url: "https://www.hhs.gov/guidance/sites/default/files/hhs-guidance-documents/FDA/Design-Control-Guidance-For-Medical-Device-Manufacturers.pdf",
    use: "Quality reference for design inputs, verification, validation, and controlled evidence; not a certification claim.",
  },
];

export const milestones: Milestone[] = [
  {
    slug: "luna-live-launch",
    productId: "luna",
    month: "AUGUST",
    date: "01 Aug",
    version: "Launch",
    title: "LUNA goes live",
    kpi: "Production access opened",
    plainMeaning: "The consumer assistant is available on web, iOS, and Android with launch training completed.",
    businessValue: "Moves LUNA from presentation promise to a service people can actually use.",
    successSignals: ["Web and mobile entry points work", "Launch users can complete the core journey", "Support and training owners are named"],
    evidence: ["Live production URL", "App distribution record", "Launch training attendance"],
    dependency: "Operational monitoring and a named incident owner.",
    state: "verified",
    release: true,
    sourceIds: [],
  },
  {
    slug: "luna-akhil-prism",
    productId: "luna",
    month: "AUGUST",
    date: "15 Aug",
    title: "AKHIL + Prism integration",
    kpi: "Usage and cost visible",
    plainMeaning: "AKHIL services and the Prism dashboard make model usage, token consumption, and operating signals visible.",
    businessValue: "Executives can see whether adoption is growing and whether the service is economical to scale.",
    successSignals: ["Requests are traceable", "Token and cost views reconcile", "Operating owners use one dashboard"],
    evidence: ["API integration check", "Dashboard screenshot", "Usage reconciliation sample"],
    dependency: "Stable identity, logging, and production telemetry.",
    state: "committed",
    sourceIds: [],
  },
  {
    slug: "luna-doctors-edition",
    productId: "luna",
    month: "SEPTEMBER",
    date: "15 Sep",
    title: "Doctors edition",
    kpi: "Clinician pilot usable",
    plainMeaning: "A clinician-oriented experience packages LUNA around real doctor workflows instead of consumer-only prompts.",
    businessValue: "Tests whether the assistant can save clinical time without weakening governance.",
    successSignals: ["Named pilot clinicians onboarded", "Priority workflow completes end to end", "Feedback is captured by workflow"],
    evidence: ["Pilot roster", "Scenario test record", "Clinical feedback summary"],
    dependency: "Clinical owner, approved content boundary, and safe escalation rules.",
    state: "target",
    sourceIds: ["who-telemedicine"],
  },
  {
    slug: "luna-reports-erx",
    productId: "luna",
    month: "OCTOBER",
    date: "15 Oct",
    title: "Reports + e-prescription",
    kpi: "Two high-value journeys connected",
    plainMeaning: "LUNA helps users understand report status and navigate an e-prescription journey through governed integrations.",
    businessValue: "Connects the assistant to repeatable hospital journeys that can reduce avoidable calls and waiting.",
    successSignals: ["Report journey returns the right status", "Prescription handoff is explicit", "Unsafe or missing data fails safely"],
    evidence: ["Journey acceptance tests", "Integration audit trail", "Safety exception review"],
    dependency: "Hospital-system integration and approved clinical wording.",
    state: "target",
    sourceIds: ["fhir"],
  },
  {
    slug: "digital-rm-v01",
    productId: "digital-rm",
    month: "SEPTEMBER",
    date: "01 Sep",
    version: "v0.1",
    title: "Initial Care RM release",
    kpi: "100% pilot leads captured",
    plainMeaning: "Every lead in the chosen pilot channel becomes a visible, owned record instead of disappearing between calls, messages, and spreadsheets.",
    businessValue: "Creates one accountable queue for patient relationships and revenue opportunities.",
    successSignals: ["Every pilot lead has an owner", "Source and service interest are recorded", "No lead can silently leave the queue"],
    evidence: ["Daily source-to-record reconciliation", "Owner coverage report", "Exception list with resolution time"],
    dependency: "One agreed pilot channel, lead definition, and responsible RM team.",
    state: "target",
    release: true,
    sourceIds: ["ahrq-care", "fhir"],
  },
  {
    slug: "digital-rm-v02",
    productId: "digital-rm",
    month: "OCTOBER",
    date: "01 Oct",
    version: "v0.2",
    title: "Follow-up + handoff release",
    kpi: "≥90% follow-ups logged",
    plainMeaning: "The team records the next action, due time, outcome, and human handoff for almost every pilot lead.",
    businessValue: "Turns follow-up from personal memory into an operational process management can improve.",
    successSignals: ["Next action has a due time", "Human handoffs keep context", "Overdue follow-ups are visible"],
    evidence: ["Follow-up coverage report", "Handoff context sample", "Overdue queue review"],
    dependency: "v0.1 lead ownership and agreed follow-up rules.",
    state: "target",
    release: true,
    sourceIds: ["ahrq-care"],
  },
  {
    slug: "digital-rm-v03",
    productId: "digital-rm",
    month: "NOVEMBER",
    date: "01 Nov",
    version: "v0.3",
    title: "Intelligence + analytics release",
    kpi: "≥80% priority coverage",
    plainMeaning: "Most active leads receive a usable priority signal so RMs can focus on the cases most likely to need action.",
    businessValue: "Moves the team from first-in-first-out work to evidence-led prioritization.",
    successSignals: ["Priority reason is visible", "Low-confidence cases are flagged", "Conversion outcomes feed the dashboard"],
    evidence: ["Priority coverage report", "Rule or model validation sample", "Outcome dashboard reconciliation"],
    dependency: "Clean follow-up and outcome history from v0.2.",
    state: "target",
    release: true,
    sourceIds: ["ahrq-care"],
  },
  {
    slug: "digital-rm-v10",
    productId: "digital-rm",
    month: "DECEMBER",
    date: "01 Dec",
    version: "v1.0",
    title: "Pilot rollout release",
    kpi: "≥90% UAT pass rate",
    plainMeaning: "The selected RM team completes agreed real-world scenarios and accepts the operating workflow for pilot use.",
    businessValue: "Provides a decision-quality signal for wider rollout instead of judging readiness from feature completion alone.",
    successSignals: ["Named users complete core scenarios", "Blocking defects have owners", "Rollout and support playbooks are ready"],
    evidence: ["Signed UAT result", "Blocking-defect register", "Pilot operating pack"],
    dependency: "Stable v0.3, approved data handling, and named pilot users.",
    state: "target",
    release: true,
    sourceIds: ["ahrq-care", "fhir"],
  },
  {
    slug: "medpac-srs-architecture",
    productId: "medpac",
    month: "AUGUST",
    date: "10–31 Aug",
    title: "SRS + architecture approval",
    kpi: "Scope baseline approved",
    plainMeaning: "The release team agrees what v1.0 must do, how the services fit together, and which interfaces must be proven.",
    businessValue: "Prevents late scope drift in a product with many external dependencies.",
    successSignals: ["Requirements have owners", "Architecture decisions are recorded", "External interfaces have test plans"],
    evidence: ["Approved SRS", "Architecture decision record", "Interface test matrix"],
    dependency: "Clinical, radiology, infrastructure, and integration owners available together.",
    state: "target",
    sourceIds: ["dicom", "fhir"],
  },
  {
    slug: "medpac-v10-readiness",
    productId: "medpac",
    month: "AUGUST",
    date: "10 Aug–30 Sep",
    version: "v1.0",
    title: "Release readiness",
    kpi: "14 external gates closed",
    plainMeaning: "Every dependency outside the core build—site, network, identity, DICOM, storage, security, support, and acceptance—has explicit evidence.",
    businessValue: "Makes hidden integration risk visible before release day.",
    successSignals: ["Every gate has an owner", "Evidence links are current", "No unresolved critical blocker"],
    evidence: ["14-gate readiness board", "Site acceptance record", "Release risk decision"],
    dependency: "Timely evidence from hospital and infrastructure owners.",
    state: "external",
    sourceIds: ["dicom"],
  },
  {
    slug: "medpac-v10-release",
    productId: "medpac",
    month: "OCTOBER",
    date: "01 Oct",
    version: "v1.0",
    title: "Early-site release gate",
    kpi: "Release decision supported by evidence",
    plainMeaning: "MedPAC is released to the selected early site only after the agreed external and technical gates are reviewed.",
    businessValue: "Protects patient-image workflows from a date-only launch decision.",
    successSignals: ["Core DICOM journeys pass", "Rollback path is proven", "Site owner accepts the release"],
    evidence: ["Go/no-go record", "DICOM conformance tests", "Early-site acceptance"],
    dependency: "All critical v1.0 readiness gates closed or formally accepted.",
    state: "external",
    release: true,
    sourceIds: ["dicom"],
  },
  {
    slug: "medpac-v11",
    productId: "medpac",
    month: "NOVEMBER",
    date: "01 Nov",
    version: "v1.1",
    title: "AI, storage + signatures",
    kpi: "Three workflow upgrades accepted",
    plainMeaning: "The next release strengthens intelligent assistance, storage operations, and trustworthy report-signing workflows.",
    businessValue: "Improves clinical throughput while keeping authoring and approval traceable.",
    successSignals: ["AI output stays assistive", "Storage lifecycle is observable", "Signature identity is auditable"],
    evidence: ["Clinical review sample", "Storage recovery test", "Signature audit trace"],
    dependency: "Stable v1.0 baseline and agreed clinical governance.",
    state: "target",
    release: true,
    sourceIds: ["dicom"],
  },
  {
    slug: "medpac-v12-his",
    productId: "medpac",
    month: "DECEMBER",
    date: "01 Dec",
    version: "v1.2",
    title: "HIS-connected release",
    kpi: "Patient-to-image journey reconciles",
    plainMeaning: "The hospital system and imaging workflow exchange the right patient, order, study, and report context without duplicate manual entry.",
    businessValue: "Connects imaging operations to the wider patient journey and reduces mismatch risk.",
    successSignals: ["Patient and order identity match", "Study status returns correctly", "Exceptions enter a visible work queue"],
    evidence: ["End-to-end reconciliation", "Interface error report", "Signed hospital acceptance"],
    dependency: "HIS interface availability, identity mapping, and stable DICOM workflows.",
    state: "target",
    release: true,
    sourceIds: ["dicom", "fhir"],
  },
  {
    slug: "teleicu-define",
    productId: "teleicu",
    month: "SEPTEMBER",
    date: "28 Sep–09 Oct",
    title: "Clinical + device definition",
    kpi: "Pilot boundary agreed",
    plainMeaning: "Clinical users and engineers agree which beds, devices, signals, alerts, and response workflow belong in the first pilot.",
    businessValue: "Keeps a safety-critical build focused on a testable first operating model.",
    successSignals: ["Named clinical owner", "Device inventory is complete", "Alert response path is explicit"],
    evidence: ["Pilot charter", "Device and signal matrix", "Escalation workflow"],
    dependency: "Access to ICU workflow owners and representative devices.",
    state: "target",
    sourceIds: ["who-telemedicine", "who-accessibility"],
  },
  {
    slug: "teleicu-gateway-alpha",
    productId: "teleicu",
    month: "OCTOBER",
    date: "10–25 Oct",
    version: "Alpha",
    title: "Gateway + dashboard alpha",
    kpi: "Representative signals visible",
    plainMeaning: "The software gateway receives the agreed sample signals and presents them in a clear remote-care dashboard.",
    businessValue: "Proves the data path before the team invests in full workflow polish.",
    successSignals: ["Signal source is identifiable", "Freshness is visible", "Disconnected devices are obvious"],
    evidence: ["Lab capture record", "Dashboard walkthrough", "Disconnect/reconnect test"],
    dependency: "Interface specification and representative device access.",
    state: "target",
    sourceIds: ["who-telemedicine"],
  },
  {
    slug: "teleicu-alert-context",
    productId: "teleicu",
    month: "OCTOBER",
    date: "26 Oct–08 Nov",
    title: "Alerts + patient context",
    kpi: "Actionable alert path works",
    plainMeaning: "Remote staff can see who the patient is, why an alert fired, and which local team must respond.",
    businessValue: "Turns raw monitor data into a governed escalation workflow.",
    successSignals: ["Patient context is correct", "Alert reason is visible", "Acknowledgement reaches the right team"],
    evidence: ["Alert scenario tests", "Context reconciliation", "Acknowledgement audit trail"],
    dependency: "Reliable identity mapping and agreed alert thresholds.",
    state: "target",
    sourceIds: ["who-telemedicine", "fhir"],
  },
  {
    slug: "teleicu-lab-uat",
    productId: "teleicu",
    month: "NOVEMBER",
    date: "09–20 Nov",
    title: "Integrated lab + clinical UAT",
    kpi: "Core scenarios pass safely",
    plainMeaning: "Clinicians and engineers run the complete monitored-bed journey with representative hardware, data loss, and escalation scenarios.",
    businessValue: "Finds operational failure modes before the system reaches a live pilot bed.",
    successSignals: ["Normal workflow completes", "Signal loss fails visibly", "Clinical users accept the response flow"],
    evidence: ["Integrated test report", "Failure-mode results", "Clinical UAT record"],
    dependency: "Gateway, interface board, PacMan node, and clinical workflow available together.",
    state: "target",
    sourceIds: ["who-telemedicine", "fda-design"],
  },
  {
    slug: "teleicu-pilot-mvp",
    productId: "teleicu",
    month: "DECEMBER",
    date: "01 Dec",
    version: "MVP",
    title: "Pilot-ready release",
    kpi: "Limited pilot can start",
    plainMeaning: "A deliberately limited TeleICU service is ready for named beds, named users, and a controlled support window.",
    businessValue: "Creates a safe learning loop without pretending the first pilot is a full production rollout.",
    successSignals: ["Pilot boundary is enforced", "Support coverage is active", "Usage and feedback are monitored"],
    evidence: ["Pilot readiness review", "Operations runbook", "Monitoring and feedback plan"],
    dependency: "Integrated software and hardware evidence, plus clinical approval.",
    state: "target",
    release: true,
    sourceIds: ["who-telemedicine", "who-accessibility"],
  },
  {
    slug: "pacman-spec-partner",
    productId: "pacman",
    month: "AUGUST",
    date: "Aug",
    title: "Specification + hardware partner",
    kpi: "Build responsibility contracted",
    plainMeaning: "The edge appliance has an agreed specification and a partner accountable for producing representative units.",
    businessValue: "Converts an architecture idea into a buildable, supportable appliance.",
    successSignals: ["Performance envelope agreed", "Partner responsibilities are explicit", "Unit acceptance method is defined"],
    evidence: ["Signed specification", "Partner work order", "Acceptance test outline"],
    dependency: "MedPAC workload profile and site constraints.",
    state: "external",
    sourceIds: ["fda-design"],
  },
  {
    slug: "pacman-evt-units",
    productId: "pacman",
    month: "SEPTEMBER",
    date: "Sep–15 Oct",
    version: "EVT",
    title: "EVT units + software image",
    kpi: "Representative units boot and run",
    plainMeaning: "Engineering units run the controlled PacMan software image and survive the agreed workload checks.",
    businessValue: "Proves hardware and software as one appliance, not two separate workstreams.",
    successSignals: ["Repeatable image install", "Thermal and performance checks pass", "Unit identity is traceable"],
    evidence: ["EVT build record", "Performance/thermal results", "Image version manifest"],
    dependency: "Partner build, stable software image, and acceptance fixtures.",
    state: "target",
    sourceIds: ["fda-design"],
  },
  {
    slug: "pacman-live-site-trial",
    productId: "pacman",
    month: "OCTOBER",
    date: "15 Oct–20 Nov",
    title: "Live-site trial",
    kpi: "Site workload remains stable",
    plainMeaning: "A controlled site runs the appliance with representative imaging traffic and visible support ownership.",
    businessValue: "Tests environmental, network, and workload assumptions that the lab cannot reproduce fully.",
    successSignals: ["Workload stays within limits", "Recovery path works", "Support issues are measurable"],
    evidence: ["Site telemetry", "Recovery drill", "Trial issue register"],
    dependency: "Accepted EVT units and an approved trial site.",
    state: "target",
    sourceIds: ["dicom", "fda-design"],
  },
  {
    slug: "pacman-mfg-ready",
    productId: "pacman",
    month: "DECEMBER",
    date: "01 Dec",
    title: "Manufacturing-ready package",
    kpi: "Repeatable build pack released",
    plainMeaning: "The partner receives the controlled bill of materials, image, assembly notes, acceptance test, and support handoff.",
    businessValue: "Makes the appliance reproducible beyond the engineering team.",
    successSignals: ["BOM and image are versioned", "Acceptance fixture is repeatable", "Support handoff is owned"],
    evidence: ["Released manufacturing pack", "Golden-unit acceptance", "Support and warranty matrix"],
    dependency: "Successful site trial and closure of critical EVT findings.",
    state: "target",
    release: true,
    sourceIds: ["fda-design"],
  },
  {
    slug: "board-interface-spec",
    productId: "interface-board",
    month: "SEPTEMBER",
    date: "28 Sep–09 Oct",
    title: "Interface + electrical specification",
    kpi: "Device boundary frozen",
    plainMeaning: "The board team agrees connectors, signals, isolation, power, firmware behavior, and the gateway-facing protocol.",
    businessValue: "Prevents hardware rework caused by ambiguous bedside-device assumptions.",
    successSignals: ["Connector and signal map complete", "Safety boundaries recorded", "Software contract versioned"],
    evidence: ["Approved interface control document", "Electrical limits table", "Protocol test vectors"],
    dependency: "Representative ICU devices and vendor interface information.",
    state: "target",
    sourceIds: ["fda-design"],
  },
  {
    slug: "board-evt1",
    productId: "interface-board",
    month: "OCTOBER",
    date: "05–30 Oct",
    version: "EVT1",
    title: "Schematic, PCB + firmware",
    kpi: "EVT1 boards assembled",
    plainMeaning: "The first engineering boards are fabricated with test firmware and documented assembly configuration.",
    businessValue: "Creates a physical system that can expose electrical and integration defects early.",
    successSignals: ["Assembly matches released files", "Firmware can identify the board", "Power-on checks are defined"],
    evidence: ["Fabrication release", "Assembly inspection", "Firmware build manifest"],
    dependency: "Frozen interface specification and component availability.",
    state: "target",
    sourceIds: ["fda-design"],
  },
  {
    slug: "board-bring-up",
    productId: "interface-board",
    month: "OCTOBER",
    date: "26 Oct–13 Nov",
    title: "Bring-up + bench checks",
    kpi: "Critical interfaces pass",
    plainMeaning: "Engineers power the board safely, exercise each critical interface, and record deviations against the specification.",
    businessValue: "Separates board defects from later software and device-integration issues.",
    successSignals: ["Power rails remain in range", "Critical I/O behaves as specified", "Failures are reproducible"],
    evidence: ["Bring-up checklist", "Bench traces", "Issue and rework record"],
    dependency: "Assembled EVT1 units and representative bench fixtures.",
    state: "target",
    sourceIds: ["fda-design"],
  },
  {
    slug: "board-integrated-lab",
    productId: "interface-board",
    month: "NOVEMBER",
    date: "09–20 Nov",
    title: "Integrated hardware/software lab",
    kpi: "End-to-end device path repeatable",
    plainMeaning: "The interface board, PacMan node, gateway, and representative bedside device exchange data through the full planned path.",
    businessValue: "Proves that individually working parts actually operate as one TeleICU system.",
    successSignals: ["Signal identity survives end to end", "Disconnects are detected", "Repeated runs produce the same result"],
    evidence: ["Integrated test matrix", "Captured data trace", "Failure/recovery results"],
    dependency: "Available TeleICU gateway, PacMan node, and device simulator or device.",
    state: "target",
    sourceIds: ["fda-design", "who-telemedicine"],
  },
  {
    slug: "board-pilot-ready",
    productId: "interface-board",
    month: "DECEMBER",
    date: "01 Dec",
    version: "EVT",
    title: "EVT pilot-ready package",
    kpi: "Controlled pilot pack released",
    plainMeaning: "A limited set of engineering boards is documented, testable, supportable, and ready for the defined TeleICU pilot environment.",
    businessValue: "Creates a controlled hardware baseline for pilot learning without claiming production certification.",
    successSignals: ["Every unit has traceability", "Known limitations are visible", "Replacement and support path is ready"],
    evidence: ["EVT release pack", "Unit acceptance records", "Known-limitations and support note"],
    dependency: "Integrated lab evidence and closure of critical hardware findings.",
    state: "target",
    release: true,
    sourceIds: ["fda-design", "who-telemedicine"],
  },
];

export const productById = Object.fromEntries(products.map((product) => [product.id, product])) as Record<ProductId, Product>;

export const milestoneBySlug = Object.fromEntries(milestones.map((milestone) => [milestone.slug, milestone])) as Record<string, Milestone>;

export const getProductMilestones = (productId: ProductId) =>
  milestones.filter((milestone) => milestone.productId === productId);

export const getReferences = (ids: string[]) => references.filter((reference) => ids.includes(reference.id));
